#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

FILE="/etc/passwd"

while read LINE
do
    echo "$LINE" | cut -d ":" -f1,3,6
done < "$FILE"
